name: cbl_ffi
version: 0.7.0-beta.11
description:
  FFI bindings for the CouchbaseLite C API and the Dart support layer.
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_ffi
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cbl_libcblite_api: 3.0.0-beta.2
  cbl_libcblitedart_api: 1.0.0-beta.6
  ffi: ^1.1.2
  meta: ^1.3.0

dev_dependencies:
  test: ^1.17.3
