name: cbl_ffi
version: 0.3.0+1
description:
  FFI bindings for the CouchbaseLite C API and the Dart support layer.
repository: https://github.com/cofu-app/cbl-dart
issue_tracker: https://github.com/cofu-app/cbl-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.0.0
  cbl_native: ^3.0.1
dev_dependencies:
  pedantic: ^1.10.0
