name: cbl_ffi
version: 0.5.1
description: FFI bindings for the CouchbaseLite C API and the Dart support layer.
repository: https://github.com/cofu-app/cbl-dart
issue_tracker: https://github.com/cofu-app/cbl-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  ffi: ^1.1.2
  cbl_native: ^4.1.0
  meta: ^1.3.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.3
