name: cbl_ffi
version: 0.8.0
description:
  FFI bindings for the CouchbaseLite C API and the Dart support layer.
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_ffi
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cbl_libcblite_api: ^3.0.0
  cbl_libcblitedart_api: ^2.0.0
  ffi: ^1.1.2
  meta: ^1.3.0

dev_dependencies:
  test: ^1.21.1
