name: cbl_ffi
version: 0.8.1
description:
  FFI bindings for the CouchbaseLite C API and the Dart support layer.
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_ffi
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: '>=2.17.4 <3.0.0'

dependencies:
  cbl_libcblite_api: ^3.0.0
  cbl_libcblitedart_api: ^4.0.0
  ffi: ^2.0.1
  meta: ^1.3.0

dev_dependencies:
  test: ^1.21.1
