name: cbl_libcblite_api
description:
  Internal marker package for declaring a dependency on a version of the
  libcblite API.
version: 3.0.2
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_libcblite_api
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'
