name: cbl_dart_repo
publish_to: none

environment:
  sdk: ^3.0.0

dev_dependencies:
  cbd:
    path: tool
  daco: ^0.3.0
  melos: ^6.2.0
  path: ^1.9.0

dependency_overrides:
  cbl:
    path: packages/cbl
