name: cbl_libcblitedart_api
description:
  Internal marker package for declaring a dependency on a version of the
  libcblitedart API.
version: 7.0.0
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_libcblitedart_api
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: ^3.0.0
