name: cbl_flutter_ce
description: Provides the Couchbase Lite Community Edition for Flutter apps.
version: 3.3.0-dev.1
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_flutter_ce
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  cbl_flutter: ^3.2.0-dev.1
  cbl_flutter_platform_interface: ^3.1.0-dev.0
  cbl_libcblite_api: 3.2.0
  cbl_libcblitedart_api: 7.1.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.terwesten.gabriel.cbl_flutter_ce
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
      ios:
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
      linux:
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
      macos:
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
      windows:
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
