name: cbl_flutter_ce
description:
  Provides the Couchbase Lite Community Edition
  for Flutter apps.
version: 1.0.0-beta.6
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_flutter_ce
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  cbl_flutter_platform_interface: ^1.0.0-beta.6
  cbl_libcblite_api: 3.0.0
  cbl_libcblitedart_api: 1.0.0
  flutter:
    sdk: flutter

flutter:
  plugin:
    implements: cbl_flutter
    platforms:
      android:
        package: com.terwesten.gabriel.cbl_flutter_ce
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
      ios:
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
      linux:
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
      macos:
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
      windows:
        pluginClass: CblFlutterCe
        dartPluginClass: CblFlutterCe
