name: cbl_flutter_platform_interface
description: Platform interface for the Couchbase Lite Flutter plugin.
version: 1.0.0
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_flutter_platform_interface
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  cbl: ^1.1.1
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
