name: cbl_flutter_prebuilt
version: 0.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  cbl: ^3.3.0-dev.1
  cbl_flutter_install: ^0.1.0-dev.1
  mustache_template: ^2.0.0
  path: ^1.8.0
  yaml: ^3.1.1
