name: cbl_sentry_example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.0.0

dependencies:
  cbl: ^3.0.0-dev.3
  cbl_dart: ^3.0.0-dev.4
  cbl_sentry:
    path: ..
  sentry: ^7.4.2
