name: cbl_sentry_example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cbl: ^2.1.1
  cbl_dart: ^2.1.3
  cbl_sentry:
    path: ..
  sentry: ^6.2.2

dev_dependencies:
  flutter_lints: ^2.0.1
