name: cbl_sentry_example
description: A simple command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cbl: ^1.1.1
  cbl_dart: ^1.1.0
  cbl_sentry:
    path: ..
  sentry: ^6.2.2

dev_dependencies:
  flutter_lints: ^1.0.0
