name: cbl_flutter_prebuilt_e2e_tests
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  cbl: ^3.1.1
  cbl_flutter: ^3.1.0
  cbl_flutter_ee:
    path: ../cbl_flutter_ee
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  # We use the latest published versions of the following packages.
  cbl: ^3.1.1
  cbl_flutter: ^3.1.0
  cbl_flutter_platform_interface: any
  cbl_libcblite_api: any
  cbl_libcblitedart_api: any
