name: cbl_flutter_prebuilt_e2e_tests
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  cbl: ^3.3.0
  cbl_flutter: ^3.2.0
  cbl_flutter_ee: ^3.3.0
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
