name: cbl_flutter_prebuilt_e2e_tests
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  cbl: ^2.2.1
  cbl_ffi: ^0.8.2+1
  cbl_flutter: ^2.0.9
  cbl_flutter_ee:
    path: ../cbl_flutter_ee
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  # We use the latest published versions of the following packages.
  # This is necessary because the current development version of cbl_ffi
  # might depend on a newer version of the binaries. The other packages
  # directly or indirectly depend on cbl_ffi.
  cbl: ^2.2.1
  cbl_ffi: ^0.8.2+1
  cbl_flutter: ^2.0.9
  cbl_flutter_platform_interface: any
  cbl_libcblite_api: any
  cbl_libcblitedart_api: any
