name: cbl_flutter_prebuilt_e2e_tests
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  cbl: any
  cbl_ffi: any
  cbl_flutter: any
  cbl_flutter_ee: any
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
