name: cbl_flutter_prebuilt_e2e_tests
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  cbl: ^1.0.0-beta.9
  cbl_flutter: ^1.0.0-beta.8
  cbl_flutter_ee: ^1.0.0-beta.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

dependency_overrides:
  cbl_flutter_ee:
    path: ../cbl_flutter_ee