name: cbl_native
version: 4.2.1
description: Binaries for CouchbaseLite + Dart.
repository: https://github.com/cofu-app/cbl-dart
issue_tracker: https://github.com/cofu-app/cbl-dart/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  http: ^0.13.0
  path: ^1.8.0
  yaml: ^3.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.2
