name: 'cbl'
version: 3.3.0-dev.4
description: >-
  Couchbase Lite is an embedded, NoSQL JSON Document Style database, supporting
  Blobs, Encryption, SQL++ Queries, Live Queries, Full-Text Search and Data
  Sync.
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

resolution: workspace

environment:
  sdk: ^3.5.0

dependencies:
  archive: ^3.6.1
  cbl_libcblite_api: ^3.1.3
  cbl_libcblitedart_api: ^8.0.0
  characters: ^1.1.0
  collection: ^1.15.0
  ffi: ^2.0.1
  http: ^1.2.2
  meta: ^1.3.0
  path: ^1.8.0
  stream_channel: ^2.1.0
  synchronized: ^3.0.0
  web_socket_channel: '>=2.1.0 <4.0.0'

dev_dependencies:
  ffigen: ^16.0.0
  test: ^1.21.1
