name: 'cbl'
version: 0.0.1
description: >-
  CouchbaseLite for Dart based on the C API. A NoSQL database with 
  change notification, full text search and replication.
repository: https://github.com/cofu-app/cbl-dart
issue_tracker: https://github.com/cofu-app/cbl-dart/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  collection: ^1.15.0-nullsafety.5
  ffi: ^0.3.0-nullsafety.1
  logging: ^1.0.0
  synchronized: ^3.0.0-nullsafety.1

dev_dependencies:
  pedantic: ^1.10.0
  test: ^1.16.0
