name: cbl_e2e_tests_flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  benchmark_harness: ^2.1.0
  cbl: ^3.4.2+0
  cbl_e2e_tests:
    path: ../cbl_e2e_tests
  cbl_flutter: ^3.3.1
  cbl_flutter_local:
    path: ../cbl_flutter_local
  collection: ^1.16.0
  crypto: ^3.0.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter
  http: ^1.0.0
  integration_test:
    sdk: flutter
  meta: ^1.7.0
  path: ^1.8.1
  path_provider: ^2.0.10
  pointycastle: ^4.0.0
  rxdart: ^0.28.0
  stream_channel: ^2.1.0
  test: ^1.21.1
  web_socket_channel: ^3.0.0
