name: 'cbl_sentry'
version: 1.0.4
description: >-
  Sentry integration for Couchbase Lite with support for recording breadcrumbs
  and performance tracing.
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_sentry
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  cbl: ^2.1.6
  sentry: ^6.11.0

dev_dependencies:
  cbl_dart: ^2.1.7
  test: ^1.21.1
