name: 'cbl_sentry'
version: 2.1.2-dev.2
description: >-
  Sentry integration for Couchbase Lite with support for recording breadcrumbs
  and performance tracing.
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_sentry
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: ^3.0.0

dependencies:
  cbl: ^3.3.0-dev.2
  sentry: ^8.0.0

dev_dependencies:
  cbl_dart: ^3.2.0-dev.2
  test: ^1.21.1
