name: cbl_e2e_tests_standalone_dart
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  cbl: ^1.0.0-beta.9
  cbl_ffi: ^0.7.0-beta.7
  collection: ^1.15.0
  http: ^0.13.3
  rxdart: ^0.26.0
  test: ^1.17.3
  web_socket_channel: ^2.1.0

dependency_overrides:
  # Normally melos should bootstrap local dependencies and handle theses 
  # overrides.
  # The problem is that running tests with `dart test` instead of `flutter test`,
  # runs `pub get` implicitly, because of the changes `melos bootstrap` makes 
  # to the dependency resolution files.
  cbl:
    path: ../cbl
  cbl_ffi:
    path: ../cbl_ffi
