name: cbl_e2e_tests_standalone_dart
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark_harness: ^2.0.0
  cbl: any
  cbl_ffi: any
  collection: ^1.15.0
  crypto: ^3.0.1
  http: ^0.13.3
  rxdart: ^0.26.0
  test: ^1.17.3
  web_socket_channel: ^2.1.0
