name: cbl_e2e_tests_standalone_dart
publish_to: none

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  benchmark_harness: ^2.1.0
  cbl: ^2.0.0
  cbl_ffi: ^0.8.0
  collection: ^1.16.0
  crypto: ^3.0.1
  http: ^0.13.4
  meta: ^1.7.0
  path: ^1.8.1
  rxdart: ^0.27.3
  stream_channel: ^2.1.0
  test: ^1.21.1
  web_socket_channel: ^2.2.0
