name: cbl_e2e_tests_standalone_dart
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dev_dependencies:
  cbl: ^1.0.0-beta.1
  cbl_ffi: ^0.7.0-beta.0
  path: ^1.8.0
  pedantic: ^1.11.0
  rxdart: ^0.26.0
  test: ^1.17.2

dependency_overrides:
  cbl:
    path: ../cbl
  cbl_ffi:
    path: ../cbl_ffi