name: cbl_e2e_tests_standalone_dart
publish_to: none

environment:
  sdk: '>=2.16.0 <3.0.0'

dependencies:
  cbl:
    path: ../cbl
  cbl_ffi:
    path: ../cbl_ffi
  collection: ^1.15.0
  crypto: ^3.0.1
  http: ^0.13.3
  rxdart: ^0.26.0
  test: ^1.17.3
  web_socket_channel: ^2.1.0

dependency_overrides:
  cbl:
    path: ../cbl
  cbl_ffi:
    path: ../cbl_ffi
