name: cbl_flutter_example
description: Demonstrates how to use the cbl_flutter plugin.
publish_to: 'none'

environment:
  sdk: '>=2.11.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  cbl: ^0.6.0
  cbl_flutter: ^0.4.0+2
  path_provider: ^2.0.1
  path: ^1.8.0

dev_dependencies:
  cbl_e2e_tests:
    path: ../../cbl_e2e_tests
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  pedantic: ^1.11.0

flutter:
  uses-material-design: true
