name: cbl_flutter
description: >-
  Flutter Plugin for Couchbase Lite, an embedded, NoSQL JSON Document Style
  database, supporting Blobs, Encryption, N1QL Queries, Live Queries, Full-Text
  Search and Data Sync.
version: 3.0.0-dev.3
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_flutter
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  cbl: ^3.0.0-dev.3
  cbl_flutter_platform_interface: ^3.0.0-dev.3
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
