name: cbl_flutter
description: >-
  Flutter Plugin for Couchbase Lite, an embedded, NoSQL JSON Document Style
  database, supporting Blobs, Encryption, N1QL Queries, Live Queries, Full-Text
  Search and Data Sync.
version: 1.0.0-beta.13
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_flutter
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: '>=2.16.0 <3.0.0'
  flutter: '>=2.10.0'

dependencies:
  cbl: ^1.0.0-beta.15
  cbl_flutter_platform_interface: ^1.0.0-beta.6
  flutter:
    sdk: flutter
  path_provider: ^2.0.1
