name: cbl_flutter
description: Binaries required to use cbl in Flutter apps.
version: 0.1.0
repository: https://github.com/cofu-app/cbl-dart
issue_tracker: https://github.com/cofu-app/cbl-dart/issues
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  cbl_ffi: ^0.2.0
  cbl_native: 2.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  pedantic: ^1.10.0

flutter:
  plugin:
    implements: cbl_flutter
    platforms:
      android:
        pluginClass: CblFlutterPlugin
        package: com.terwesten.gabriel.cbl_flutter
      ios:
        pluginClass: CblFlutterPlugin
      macos:
        pluginClass: CblFlutterPlugin
