name: cbl_flutter
description: >-
  Flutter Plugin for Couchbase Lite, an embedded, NoSQL JSON Document Style
  database, supporting Blobs, Encryption, SQL++ Queries, Live Queries, Full-Text
  Search and Data Sync.
version: 3.3.1
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_flutter
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: ^3.0.0
  flutter: '>=3.0.0'

dependencies:
  cbl: ^3.4.2+0
  cbl_flutter_platform_interface: ^3.1.2
  flutter:
    sdk: flutter
  path_provider: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.terwesten.gabriel.cbl_flutter
        pluginClass: CblFlutterPlugin
