name: cbl_e2e_tests
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cbl: ^1.0.0-beta.5
  cbl_ffi: ^0.7.0-beta.4
  collection: ^1.15.0
  http: ^0.13.3
  rxdart: ^0.26.0
  test: ^1.17.3
  web_socket_channel: ^2.1.0
