name: cbl_e2e_tests
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  cbl: ^0.5.1
  cbl_ffi: ^0.5.1
  logging: ^1.0.1
  rxdart: ^0.26.0
  test: ^1.16.0

dev_dependencies:
  pedantic: ^1.11.0
