name: cbl_e2e_tests
publish_to: none

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  cbl:
    path: ../cbl
  cbl_ffi: ^0.2.0
  logging: ^1.0.0
  test: ^1.16.0

dev_dependencies:
  pedantic: ^1.10.0
