name: cbl_generator
version: 0.3.0-dev.3
description:
  Code generator for Couchbase Lite, which is an embedded, NoSQL JSON Document
  Style database.
homepage: https://github.com/cbl-dart/cbl-dart/tree/main/packages/cbl_generator
repository: https://github.com/cbl-dart/cbl-dart
issue_tracker: https://github.com/cbl-dart/cbl-dart/issues

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^6.0.0
  build: ^2.3.0
  build_config: ^1.0.0
  cbl: ^3.0.0-dev.3
  collection: ^1.15.0
  meta: ^1.7.0
  source_gen: ^1.2.2
  source_helper: ^1.3.2

dev_dependencies:
  build_runner: ^2.1.10
  build_test: ^2.1.5
  cbl_dart: ^3.0.0-dev.4
  path: ^1.8.1
  test: ^1.21.1
